import LoginPage from "../support/PageObject/LoginPage"
import DatePicker from "../support/PageObject/DatePicker"
import MessageWidget from "../support/PageObject/MessageWidget"

describe('Klik button "+ new cluster"', () => {
  beforeEach(() => {
    LoginPage.visit();
  })
  it('Should New Cluster currently added', () => {
    cy.viewport(1280, 720)
    LoginPage.fillCredentials("sa1", "123456")
    cy.get('#b2-LinkManage').should('have.text', "Manage")
    cy.get('#b2-LinkManage').click()
    cy.url().should('include', '/SML_BankOfProject_Web/Manage')
    cy.get('#TabsHeaderItemCluster .osui-tabs__header-item').click()
    cy.get('#b16-ButtonNewCluster').click()
    cy.get('#b16-PopupEdit').should('be.visible')
    cy.contains('label', 'Project')
    cy.get('select#b16-Dropdown2').select('GOPEK')
    cy.contains('label', 'Building Type')
    cy.get('select#b16-Dropdown1').select('High Rise')
    cy.contains('label', 'Cluster Code')
    cy.get('#b16-Input_ProjectCode').type('0001')
    cy.contains('label', 'Cluster Name')
    cy.get('#b16-Input_ProjectName').type('Cluster Angkasa')
    cy.contains('label', 'Description')
    cy.get('#b16-Input_Description').type('Ini Description')
    cy.contains('label', 'Start Date')
    DatePicker.fillDatePicker("b16-b4-DatepickerAccessibilityInfo", 2025, "February", 21)
    cy.contains('label', 'End Date')
    DatePicker.fillDatePicker("b16-b5-DatepickerAccessibilityInfo", 2025, "February", 22)
    cy.contains('label', 'Is Active')
    
    cy.get('#b16-SaveNewCluster').click()
    MessageWidget.getWarningMessage("Cluster recently added!")
  })
  it('Should New Cluster successfully added', () => {
    cy.viewport(1280, 720)
    LoginPage.fillCredentials("sa1", "123456")
    cy.get('#b2-LinkManage').should('have.text', "Manage")
    cy.get('#b2-LinkManage').click()
    cy.url().should('include', '/SML_BankOfProject_Web/Manage')
    cy.get('#TabsHeaderItemCluster .osui-tabs__header-item').click()
    cy.get('#b16-ButtonNewCluster').click()
    cy.get('#b16-PopupEdit').should('be.visible')
    cy.contains('label', 'Project')
    cy.get('select#b16-Dropdown2').select('GOPEK')
    cy.contains('label', 'Building Type')
    cy.get('select#b16-Dropdown1').select('High Rise')
    cy.contains('label', 'Cluster Code')
    cy.get('#b16-Input_ProjectCode').type('0003')
    cy.contains('label', 'Cluster Name')
    cy.get('#b16-Input_ProjectName').type('Cluster Angkasa III')
    cy.contains('label', 'Description')
    cy.get('#b16-Input_Description').type('Ini Description')
    cy.contains('label', 'Start Date')
    DatePicker.fillDatePicker("b16-b4-DatepickerAccessibilityInfo", 2025, "February", 21)
    cy.contains('label', 'End Date')
    DatePicker.fillDatePicker("b16-b5-DatepickerAccessibilityInfo", 2025, "February", 22)
    cy.contains('label', 'Is Active')

    cy.get('#b16-SaveNewCluster').click()
    MessageWidget.getSuccessMessage("Cluster Successfully Added!")
  })
})